version: '2.4'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spotify-search
    container_name: spotify-search-main-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage:delegated
      - vendor:/var/www/vendor
    networks:
      - spotify-search
    depends_on:
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: spotify-search-main-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - vendor:/var/www/vendor
    networks:
      - spotify-search
    depends_on:
      - app

  # Redis Service
  redis:
    image: redis:alpine
    container_name: spotify-search-main-redis
    restart: unless-stopped
    networks:
      - spotify-search
    ports:
      - "6380:6379"

  # Queue Worker Service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-search-main-queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage:delegated
      - vendor:/var/www/vendor
    command: php artisan queue:work --tries=3 --timeout=90
    networks:
      - spotify-search
    depends_on:
      - app
      - redis

networks:
  spotify-search:
    driver: bridge

volumes:
  vendor:
    driver: local 